### ISSUE TITLE
if unlucky installing GenABEL 1.8.0 install devtools and try ...

### ISSUE THREAD

**Issue by rafalcode** [monogenea/GWAStutorial#2]
Rscript -e "library(devtools); install_github('rafalcode/GenABEL.data'); install_github('rafalcode/             GenABEL');"

**Comment by monogenea** [comment]
nice one! thanks @rafalcode

**Comment by skr3178** [comment]
Removing an extra space

`library(devtools); install_github('rafalcode/GenABEL.data'); install_github('rafalcode/GenABEL');`

**Comment by skr3178** [comment]
`install_github('rafalcode/GenABEL')`

Downloading GitHub repo rafalcode/GenABEL@HEAD
✔  checking for file 'C:\Users\skr\AppData\Local\Temp\RtmpeUthBM\remotes47ac2df52771\rafalcode-GenABEL-eddf1fb/DESCRIPTION' (478ms)
─  preparing 'GenABEL': (349ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (368ms)
─  checking for empty or unneeded directories
─  building 'GenABEL_1.8-0.tar.gz'
   
Installing package into ‘C:/Users/skr/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'GenABEL' ...
** using staged installation
** libs
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c AbstractMatrix.cpp -o AbstractMatrix.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c AbstractMatrix_R.cpp -o AbstractMatrix_R.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c CastUtils.cpp -o CastUtils.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c Chip.cpp -o Chip.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c FileVector.cpp -o FileVector.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c FilteredMatrix.cpp -o FilteredMatrix.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c FilteredMatrix_R.cpp -o FilteredMatrix_R.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c Logger.cpp -o Logger.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RealHandlerWrapper.cpp -o RealHandlerWrapper.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c ReusableFileHandle.cpp -o ReusableFileHandle.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c Transposer.cpp -o Transposer.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c chinv2.cpp -o chinv2.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c cholesky2.cpp -o cholesky2.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c chsolve2.cpp -o chsolve2.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c convert.snp.affymetrix.cpp -o convert.snp.affymetrix.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c convert_snp_illumina.cpp -o convert_snp_illumina.o
convert_snp_illumina.cpp: In function 'void convert_snp_illumina(char**, char**, int*, int*, char**, int*)':
convert_snp_illumina.cpp:209:11: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
  209 |    catch (bad_alloc) {
      |           ^~~~~~~~~
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c convert_snp_merlin.cpp -o convert_snp_merlin.o
convert_snp_merlin.cpp: In function 'void convert_snp_merlin(char**, char**, char**, int*, int*, char**, int*, int*, int*, int*)':
convert_snp_merlin.cpp:310:10: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
  310 |   catch (bad_alloc) {
      |          ^~~~~~~~~
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c convert_snp_merlin_wslash.cpp -o convert_snp_merlin_wslash.o
convert_snp_merlin_wslash.cpp: In function 'void convert_snp_merlin_wslash(char**, char**, char**, int*, int*, char**, int*, int*, int*, int*)':
convert_snp_merlin_wslash.cpp:334:10: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
  334 |   catch (bad_alloc) {
      |          ^~~~~~~~~
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c convert_snp_tped.cpp -o convert_snp_tped.o
convert_snp_tped.cpp: In function 'void convert_snp_tped(char**, char**, char**, int*, int*, char**, int*)':
convert_snp_tped.cpp:181:11: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
  181 |    catch (bad_alloc) {
      |           ^~~~~~~~~
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c convert_util.cpp -o convert_util.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c coxfit2.cpp -o coxfit2.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c dautil.cpp -o dautil.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c dmatrix.cpp -o dmatrix.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c dometa.cpp -o dometa.o
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DCOMPILE_WITH_R   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c export_plink.cpp -o export_plink.o
export_plink.cpp: In function 'SEXPREC* export_plink(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)':
export_plink.cpp:116:56: warning: array subscript has type 'char' [-Wchar-subscripts]
  116 |             fileWoA << " " << Genotype[gtMatrix[i][csnp]];
      |                                        ~~~~~~~~~~~~~~~~^
gcc  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c fexact.c -o fexact.o
fexact.c: In function 'f3xact':
fexact.c:1025:6: error: 'PROBLEM' undeclared (first use in this function)
 1025 |      PROBLEM "Bug in FEXACT: gave negative key" RECOVER(NULL_ENTRY);
      |      ^~~~~~~
fexact.c:1025:6: note: each undeclared identifier is reported only once for each function it appears in
fexact.c:1025:13: error: expected ';' before string constant
 1025 |      PROBLEM "Bug in FEXACT: gave negative key" RECOVER(NULL_ENTRY);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             ;
fexact.c: In function 'prterr':
fexact.c:1806:5: error: 'PROBLEM' undeclared (first use in this function)
 1806 |     PROBLEM "FEXACT error %d.\n%s", icode, mes RECOVER(NULL_ENTRY);
      |     ^~~~~~~
fexact.c:1806:12: error: expected ';' before string constant
 1806 |     PROBLEM "FEXACT error %d.\n%s", icode, mes RECOVER(NULL_ENTRY);
      |            ^~~~~~~~~~~~~~~~~~~~~~~
      |            ;
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:253: fexact.o] Error 1
ERROR: compilation failed for package 'GenABEL'
* removing 'C:/Users/skr/AppData/Local/R/win-library/4.2/GenABEL'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/skr/AppData/Local/Temp/RtmpeUthBM/file47ac4f64a9f/GenABEL_1.8-0.tar.gz’ had non-zero exit status
